pulls:
# Enable for pull requests
  perform: true
issues:
# set to true to enable for issues
  perform: true
# issues with these labels will be considered. Set to `[]` to disable for issues
  labels:
    - help wanted
