language: python
python:
    - "2.7"

sudo: required

# Travis build script for RenPy
# based on Monika-After-Story script.
  
env:
    # this is required as there was build issues without this, don't remove this.
    - SDL_AUDIODRIVER=dummy SDL_VIDEODRIVER=dummy

# This is the script part. This is where the actual building is happening.
# This produces an artifact which we'll use later on to publish a release.

script: cd .. && bash the-angel-returns/scripts/ci.sh && ls

# This is where the actual releases happen. Travis has the ability to publish releases from GitHub, Amazon S3, OpenShift, etc.
# Read on https://docs.travis-ci.com/user/deployment/releases/ to learn more
# For this type of configuration, we're using the GitHub releases schema

deploy:
  provider: releases
  api_key:
    # DO NOT CHANGE THIS! Travis can replace this since it's a Environment Variable.
    # Head to Settings > Environment variables and set this.
    secure: $GITHUB_API_KEY
  file_glob: true
  file: "*-dists/*-Mod.zip"
  skip_cleanup: true
  on:
    tags: true # your mods only builds and uploads releases on a GitHub Git tag so make sure you tag and release accordingly!

notifications:
  webhooks:
    - https://ddtar-webhook.mybluemix.net/webhook/travis