theme: jekyll-theme-cayman
show_downloads: true
name: Doki Doki - The Angel Returns
title: The Angel Returns
description: Join the Literature Club girls in an ever-exciting adventure to Joey Drew Studios during the spring break! Remember to pay a good ol’ visit to the Angel and… [ JUST ALICE ]

github:
  zip_url: https://github.com/alicerunsonfedora/the-angel-returns/releases/download/0.1.1/Demo.Release.zip
